num_1 = int(input('Enter integer: '))

print('int: ', num_1)
print('bool: ', bool(num_1))
print('float: ', float(num_1))
print('str: ', str(num_1))

num_2 = int(input('Enter one more integer: '))
print()
print('num1 as int and num2 as ...')
print('int: {0} + {1} = {2}, {0} * {1} = {3}'.format(int(num_1), int(num_2), (int(num_1) + int(num_2)), (int(num_1) * int(num_2))))
print('float: {0} + {1} = {2}, {0} * {1} = {3}'.format(int(num_1), float(num_2), (int(num_1) + float(num_2)), (int(num_1) * float(num_2))))
print('bool: {0} + {1} = {2}, {0} * {1} = {3}'.format(int(num_1), bool(num_2), (int(num_1) + bool(num_2)), (int(num_1) * bool(num_2))))
print()
print('num1 as bool and num2 as ...')
print('int: {0} + {1} = {2}, {0} * {1} = {3}'.format(bool(num_1), int(num_2), (bool(num_1) + int(num_2)), (bool(num_1) * int(num_2))))
print('float: {0} + {1} = {2}, {0} * {1} = {3}'.format(bool(num_1), float(num_2), (bool(num_1) + float(num_2)), (bool(num_1) * float(num_2))))
print('bool: {0} + {1} = {2}, {0} * {1} = {3}'.format(bool(num_1), bool(num_2), (bool(num_1) + bool(num_2)), (bool(num_1) * bool(num_2))))
print()
print('num1 as float and num2 as ...')
print('int: {0} + {1} = {2}, {0} * {1} = {3}'.format(float(num_1), int(num_2), (float(num_1) + int(num_2)), (float(num_1) * int(num_2))))
print('float: {0} + {1} = {2}, {0} * {1} = {3}'.format(float(num_1), float(num_2), (float(num_1) + float(num_2)), (float(num_1) * float(num_2))))
print('bool: {0} + {1} = {2}, {0} * {1} = {3}'.format(float(num_1), bool(num_2), (float(num_1) + bool(num_2)), (float(num_1) * bool(num_2))))
print()
print('num1 as str and num2 as ...')
print('str: {0} + {1} = {2}'.format(str(num_1), str(num_2), (str(num_1) + str(num_2))))
print('int: {0} * {1} = {2}'.format(str(num_1), int(num_2), (str(num_1) * int(num_2))))
